### ISSUE TITLE
Can I use the systemd install version of nginx? 

### ISSUE THREAD

**Issue by iconoclasthero** [rawdlite/docker-rompr#9]
It looks like you've packaged nginx inside the docker and I have the RP setup as a systemd service, not in a docker to serve audiobookshelf and gonic at the moment.  I can't imagine it's going to be easy to configre a second nginx instance inside a docker to work aside the systemd one.

**Comment by rawdlite** [comment]
Actually the whole reason for docker is to have an nginx and other software run independently and alongside your system install. Think of docker as a computer inside a computer.
HTH
